#!/usr/bin/env php
<?php
if (isset($argv[1]) && $argv[1] === 'data:parse') {
    $input  = $argv[2] ?? __DIR__ . '/data/data.csv';
    $output = $argv[3] ?? __DIR__ . '/data/data.json';

    $input  = strstr($input, '=', false) ?: $input;
    $output = strstr($output, '=', false) ?: $output;

    require_once __DIR__ . '/app/Parser.php';
    App\Parser::parse($input, $output);
    exit(0);
}

require_once __DIR__ . '/vendor/autoload.php';

\Tempest\Console\ConsoleApplication::boot(loadBuiltInCommands: false)->run();