#!/usr/bin/env php
<?php
if (isset($argv[1]) && $argv[1] === 'data:parse') {
    require __DIR__ . '/app/Parser.php';
    App\Parser::parse(
        $argv[2] ?? __DIR__ . '/data/data.csv',
        $argv[3] ?? __DIR__ . '/data/data.json'
    );
    exit(0);
}